version: 0.0
os: linux

files:
  - source: ${{ inputs.SOURCE_PATH }}
    destination: /usr/share/nginx/html_nova/nova/
    overwrite: yes

hooks:
  AfterInstall:
    - location: scripts/reload_nginx.sh
      timeout: 60
      runas: ec2-user
