name: Build and Deploy to AWS EC2

on:
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:
  build:
    name: Build Project
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    timeout-minutes: 30
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
        with:
          repository: aspyn-y-kwon/ServerDevTeam-WAS
          ref: main
          token: ${{ secrets.PAT }} 
          path: ./source-code
          fetch-depth: 0
          persist-credentials: false
          
      # - name: Set up SVN Client
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y subversion

      # - name: Checkout Code from SVN with Authentication
      #   run: |
      #     svn checkout https://tr00058.infraware.net/svn/PolarisCloud/Server/projects/PolarisCloudService/trunk/ \
      #     --username ${{ secrets.SVN_USERNAME }} \
      #     --password ${{ secrets.SVN_PASSWORD }} \
      #     ./source-code       

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      # - name: Set up Maven 
      #   run: sudo apt-get install -y maven

      - name: Set up Maven 3.6.3
        run: |
          # wget https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
          # sudo tar -xvzf apache-maven-3.6.3-bin.tar.gz
          # sudo mv apache-maven-3.6.3 /opt/maven
          # echo "export MAVEN_HOME=/opt/maven" >> $GITHUB_ENV
          # echo "export PATH=\$MAVEN_HOME/bin:\$PATH" >> $GITHUB_ENV
          MAVEN_VERSION=3.6.3
          MAVEN_DOWNLOAD_URL=https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
          
          # Download Maven
          curl -L ${MAVEN_DOWNLOAD_URL} -o maven.tar.gz
          
          # Extract Maven
          sudo mkdir -p /opt/maven
          sudo tar -xzf maven.tar.gz -C /opt/maven --strip-components=1
          
          # Set environment variables
          echo "M2_HOME=/opt/maven" >> $GITHUB_ENV
          echo "PATH=/opt/maven/bin:$PATH" >> $GITHUB_ENV
          
          # Clean up
          rm maven.tar.gz
          

      - name: Verify Maven Installation
        # run: mvn -v
        run: |
          echo "M2_HOME: $M2_HOME"
          echo "PATH: $PATH"
          mvn -v

      - name: Build with Maven (WAR)
        run: mvn clean package --file ./source-code/pom.xml

      - name: Copy appspec.yml and scripts to source-code directory
        run: |
          cp appspec.yml ./source-code/
          mkdir -p ./source-code/scripts
          cp scripts/deploy_root.sh ./source-code/scripts/

      - name: Compress Build Artifact
        run: tar -cvzf build.tar.gz ./source-code/target/*.war ./source-code/appspec.yml ./source-code/scripts/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Upload to S3
        env:
          AWS_S3_BUCKET: tb-ca-github-actions
        run: |
          aws s3 cp build.tar.gz s3://${{ env.AWS_S3_BUCKET }}/build.tar.gz


  deploy:
    name: Deploy to EC2 via CodeDeploy
    needs: build
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Deploy with AWS CodeDeploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}
          AWS_CODEDEPLOY_APP : github-actions
          AWS_DEPLOY_GROUP : Deploy_EC2
          AWS_S3_BUCKET : tb-ca-github-actions
        run: |
          aws deploy create-deployment \
          --application-name ${{ env.AWS_CODEDEPLOY_APP }} \
          --deployment-group-name ${{ env.AWS_DEPLOY_GROUP }} \
          --s3-location bucket=${{ env.AWS_S3_BUCKET }},bundleType=tgz,key=build.tar.gz \
          --file-exists-behavior OVERWRITE
